# General settings
working_dir: "/Users/rafayshahood/Desktop/adn/clinic-net/output"  # Set the output directory
id: "v3"  # Configuration version
seeds:
  - 32
dry_run: False  # For testing; if True, only one training iteration is performed

# Data settings
data:
  slices_range: 120  # Slices range around the middle coronal plane
  quality_check: False  # Set to False if no mmse data is available
  col_names:  # Columns from the CSV that will be used
    - participant_id
    - session_id
    - diagnosis
    - age
    - sex
  valid_dataset_names:  # Include the ADNI1 dataset name
    - ADNI1
  diagnoses_info:
    valid_diagnoses:
      - CN
      - AD
      - MCI
    control_labels:  # Encoded as 'CN'
      - CN
    ad_labels:  # Encoded as 'AD'
      - AD
    mci_labels:  # Encoded as 'MCI'
      - MCI

# NNCLR settings
nnclr:
  checkpoint_resume: ""  # Path to checkpoint if resuming training
  epochs: 2
  save_nepoch: 2  # Save model every nth epoch
  batch_size: 180
  trainable_layers: 0  # Number of trainable layers; 0 means all are trainable
  data:
    - caps_directories:
        - "/Users/rafayshahood/Desktop/adn/clinic-net/ADNI"  # Dataset path
    - info_data_files:
        - "/Users/rafayshahood/Desktop/adn/clinic-net/ADNI/ADNI1_002_S data file.csv"  # CSV file path

# Classifier settings
classifier:
  epochs: 2
  batch_size: 64
  replicas: 100  # Number of randomly selected slices per sample for diagnosis prediction
  replicas_extraction: 1  # Extract features from random slices
  comparison: True  # If True, trains a model with and without freezing the backbone
  eval_labels:  # Labels used for evaluation
    - CN
    - AD
  data:
    - caps_directories:
        - "/Users/rafayshahood/Desktop/adn/clinic-net/ADNI"
    - info_data_files:
        - "/Users/rafayshahood/Desktop/adn/clinic-net/ADNI/ADNI1_002_S data file.csv"

# Independent evaluation settings
independent_evaluation:
  seed: 1
  checkpoint_load: "/Users/rafayshahood/Desktop/adn/clinic-net/output/checkpoints/classifier_seed-32_freeze-True_conf_id-v3.pt"
  batch_size: 128
  replicas: 100
  replicas_extraction: 1
  data:
    - caps_directories:
        - "/Users/rafayshahood/Desktop/adn/clinic-net/adni2"
    - info_data_files:
        - "/Users/rafayshahood/Desktop/adn/clinic-net/adni2/ADNI1_Complete_1Yr_1.5T_11_02_2024.csv"  # CSV file path
  eval_labels:
    - CN
    - AD

# Visualization settings
visualisation:
  backbone_checkpoint: "/Users/rafayshahood/Desktop/adn/clinic-net/output/checkpoints/nnclr_seed-32_conf_id-v3"
  classifier_checkpoint: "/Users/rafayshahood/Desktop/adn/clinic-net/output/checkpoints/classifier_seed-32_freeze-True_conf_id-v3.pt"
  log_dir: "/Users/rafayshahood/Desktop/adn/clinic-net/output/logs/"
